services:
  app:
    build:
      context: docker/app
    volumes:
      - ./:/workspace
      - ./tmp/.go/pkg:/go/pkg
      - ./tmp/.go-cache:/go-cache
    working_dir: /workspace
    env_file:
      - .env
    ports:
      - "$PORT:$PORT"
    environment:
      GOCACHE: /go-cache
      DATA_FOLDER: ${DATA_FOLDER}
      API_KEY: ${API_KEY}
